web: vendor/bin/heroku-php-apache2 public/
composer require symfony/apache-pack

# api/config/packages/api_platform.yaml
-    http_cache:
-        invalidation:
-            enabled: true
-            varnish_urls: ['%env(VARNISH_URL)%']
-        max_age: 0
-        shared_max_age: 3600
-        vary: ['Content-Type', 'Authorization', 'Origin']
-        public: true